import { CalculatorButtonI } from "@/interface";

const ButtonsData: CalculatorButtonI[]=[
    {
        label:"C",
        variant:"action"
    },
    {
        label:"+/-",
        variant:"action"
    },
    {
        label:"del",
        variant:"action"
    },
    {
        label:"/",
        variant:"operator"
    },
    {
        label:"7",
        variant:"number"
    },
    {
        label:"8",
        variant:"number"
    },
    {
        label:"9",
        variant:"number"
    },
    {
        label:"x",
        variant:"operator"
    },
    {
        label:"4",
        variant:"number"
    },
    {
        label:"5",
        variant:"number"
    },
    {
        label:"6",
        variant:"number"
    },
    {
        label:"-",
        variant:"operator"
    },
    {
        label:"1",
        variant:"number"
    },
    {
        label:"2",
        variant:"number"
    },
    {
        label:"3",
        variant:"number"
    },
    {
        label:"+",
        variant:"operator"
    },
    {
        label:"0",
        variant:"number"
    },
    {
        label:".",
        variant:"number"
    },
    {
        label:"=",
        variant:"operator"
    }
]

export default ButtonsData;